blueprint:
  name: Motion Sensor Auto Setup
  description: Install a 433 MHz motion sensor
  domain: automation

trigger:
  -  platform: mqtt
     topic: tele/rfbridge/RESULT
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{trigger.payload_json.RfReceived.Sync | int > 12000 }}'
  - condition: template
    value_template: '{{trigger.payload_json.RfReceived.Sync | int < 13801 }}'
  - condition: state
    entity_id: input_boolean.door_sensor_discovery
    state: 'on'
  - condition: or
    conditions:
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "E" }}'
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "B" }}'
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "6" }}'
action:
  - service: mqtt.publish
    data_template:
      topic: '{{ ''homeassistant/binary_sensor/batt_state'' + trigger.payload_json.RfReceived.Data[:5]
        + ''/config'' }}'
      payload: "{\n  \"name\": \"{{ 'Motion Battery ' + trigger.payload_json.RfReceived.Data[:5]}}\"\
        ,\n  \"stat_t\": \"~BATT_STATE\",\n  \"device_class\": \"battery\",\n  \"\
        uniq_id\": \"{{ 'Batt-' + trigger.payload_json.RfReceived.Data[:5]}}\",\n\
        \  \"device\": {\n    \"identifiers\": [\n      \"{{trigger.payload_json.RfReceived.Data[:5]}}\"\
        \n    ],\n  \"name\": \"{{ 'Motion ' + trigger.payload_json.RfReceived.Data[:5]}}\"\
        ,\n  \"model\": \"Motion Sensor\"\n,\n  \"manufacturer\": \"VirageLabs\"\n\
        \  },\n  \"~\": \"{{ trigger.payload_json.RfReceived.Data[:5] + '/tele/' }}\"\
        \n}"
      retain: true
  - service: mqtt.publish
    data_template:
      topic: '{{ ''homeassistant/binary_sensor/motion_state'' + trigger.payload_json.RfReceived.Data[:5]
        + ''/config'' }}'
      payload: "{\n  \"name\": \"{{ 'Motion State ' + trigger.payload_json.RfReceived.Data[:5]}}\"\
        ,\n  \"stat_t\": \"~MOTION_STATE\",\n  \"device_class\": \"motion\",\n  \"\
        off_delay\": \"1\",\n  \"uniq_id\": \"{{ 'State-' + trigger.payload_json.RfReceived.Data[:5]}}\"\
        ,\n  \"device\": {\n    \"identifiers\": [\n      \"{{trigger.payload_json.RfReceived.Data[:5]}}\"\
        \n    ]\n  },\n  \"~\": \"{{ trigger.payload_json.RfReceived.Data[:5] + '/tele/'\
        \ }}\"\n}"
      retain: true
  - service: input_boolean.turn_off
    entity_id: input_boolean.door_sensor_discovery
